name: doctorisinapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  loading_animation_widget: ^1.3.0
  flutter_typeahead: ^5.2.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_lints: ^5.0.0
  http: 1.3.0
  easy_localization: ^3.0.0
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  flutter_pdfview: ^1.0.4
  url_launcher: ^6.0.20  # Add url_launcher package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ekids1.png"

flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/bronze_package.png
    - assets/silver_package.png
    - assets/gold_package.png
    - assets/ekids1.png
    - assets/Animation - 1737674553839.gif
    - assets/Animation - 1738296418740.gif
    - assets/translations/
    - assets/Chatting.png
    - assets/checklist.gif
    - assets/ekids11.png
    - assets/doctor_avatar.png
    - assets/login.png
    - assets/Profile pics/Dog.jpeg
    - assets/Profile pics/Fox.jpeg
    - assets/Profile pics/Rabbit.jpeg

  fonts:
    - family: ComicSansMS
      fonts:
        - asset: assets/fonts/ComicSansMS.ttf
